"use client";
import {FormEvent,useState} from "react";
const stories=[["Life Legacy","One extraordinary life."],["Family Chronicle","A history across generations."],["Immigrant Journey","The courage to begin again."],["Founder Story","The person behind what was built."],["Legacy Tribute","A life reconstructed with care."]];
const steps=["Listen","Explore","Shape","Prepare","Film","Edit","Review","Deliver","Preserve"];
const faqs=[["What is a Family Legacy Film?","A professionally authored documentary preserving a life, family, journey, business or cultural inheritance for future generations."],["How is this different from a videographer?","We develop the story before filming, then combine research, interviews, archives, observation, sound and documentary editing. The result is a film—not simply a recording."],["How much does a project cost?","Private commissions typically begin above $30,000. After discovery, you receive a written proposal covering scope, schedule, deliverables and investment."],["Can our film remain private?","Yes. Private review and delivery are the default. Nothing is published without explicit written permission."],["Can you use photographs and home movies?","Yes. Photographs, letters, recordings, documents and home movies can be digitized and woven into the film."],["What if our family is in several cities?","We design multi-location productions and quote travel transparently."],["How long does it take?","Most films unfold over several months. Your proposal defines research, production, review and delivery milestones."]];
export default function Home(){const[sent,setSent]=useState(false);const submit=(e:FormEvent)=>{e.preventDefault();setSent(true)};return <main>
<header><a className="logo" href="#top"><b>GREEN ROAD</b><small>FAMILY LEGACY FILMS</small></a><nav><a href="#stories">Stories</a><a href="#films">Films</a><a href="#method">Method</a><a href="#faq">FAQ</a></nav><a className="ask" href="#contact">Begin privately ↗</a></header>
<section className="hero" id="top"><div className="hero-copy"><p className="eyebrow">Private documentary atelier · California</p><h1>Lives worth<br/>remembering,<br/><em>beautifully.</em></h1><p>Deeply personal documentary films for families who want their stories to live beyond memory.</p><a className="button filled" href="#contact">Tell us your story <span>↗</span></a></div><figure><img src="https://images.pexels.com/photos/6972627/pexels-photo-6972627.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="A mature couple reflecting on their family photographs"/><figcaption>PRIVATE COMMISSION / A lifetime held in one frame</figcaption></figure></section>
<section className="purpose"><p className="eyebrow">01 / OUR PURPOSE</p><div><h2>Memory fades.<br/><em>A story can endure.</em></h2><p>A voice, a childhood kitchen, a journey across borders, the business built from nothing—these details carry a family’s meaning.</p></div><aside>Our work begins with listening.<br/><b>Only then, the camera.</b></aside></section>
<section className="archive"><img src="https://images.pexels.com/photos/10948905/pexels-photo-10948905.jpeg?auto=compress&cs=tinysrgb&w=2200" alt="Hands holding a treasured old family photograph"/><div><p>ARCHIVE / VOICE / PLACE</p><h2>We turn the things you kept into the story <em>they were keeping.</em></h2></div></section>
<section className="story-section" id="stories"><div className="title"><p className="eyebrow">02 / STORY TERRITORIES</p><h2>What should never<br/>be forgotten?</h2></div><div className="story-list">{stories.map((s,i)=><article key={s[0]}><span>0{i+1}</span><h3>{s[0]}</h3><p>{s[1]}</p><i>↗</i></article>)}</div></section>
<section className="films" id="films"><div className="film-image"><img src="https://images.pexels.com/photos/8307718/pexels-photo-8307718.jpeg?auto=compress&cs=tinysrgb&w=2000" alt="Grandparents sharing family memories with a younger generation"/><span>THE FAMILY DOCUMENTARY</span></div><div className="film-copy"><p className="eyebrow">03 / THE COMMISSION</p><h2>Not a video.<br/><em>A family heirloom.</em></h2><p>Research, intimate interviews, cinematic observation and family archives become one carefully authored film.</p>{[["01","The Legacy Film","25–45 minutes · intimate"],["02","The Family Documentary","45–75 minutes · intergenerational"],["03","The Family Feature","60–90+ minutes · signature"]].map(x=><div className="level" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small></div>)}<a className="button outline" href="#contact">Discuss your commission ↗</a><small>Private commissions typically begin above $30,000.</small></div></section>
<section className="method" id="method"><div className="title"><p className="eyebrow">04 / OUR METHOD</p><h2>A quiet process.<br/><em>A lasting result.</em></h2></div><div className="steps">{steps.map((s,i)=><article key={s}><span>0{i+1}</span><h3>{s}</h3><p>{["A private first conversation.","Find the story beneath the story.","Build the narrative before production.","Research people, places and archives.","A small crew, a calm environment.","Discover emotional truth in the edit.","A respectful, defined review.","Private 4K delivery.","Created to live for generations."][i]}</p></article>)}</div></section>
<section className="privacy"><p className="eyebrow">PRIVATE BY DESIGN</p><blockquote>Your family’s story remains <em>your family’s.</em></blockquote><p>Nothing is published without explicit permission. Controlled review · Private delivery · Archival care.</p></section>
<section className="rating"><div><p className="eyebrow">05 / SAN FRANCISCO</p><h2>Trust is part<br/>of the craft.</h2></div><aside><span>★★★★★</span><h3>Google rating</h3><p>Ready to connect to the San Francisco Google Business Profile.</p></aside></section>
<section className="faq" id="faq"><div className="title"><p className="eyebrow">06 / BEFORE WE BEGIN</p><h2>Questions,<br/><em>answered quietly.</em></h2></div><div>{faqs.map((f,i)=><details key={f[0]} open={i===0}><summary><span>0{i+1}</span>{f[0]}<i>+</i></summary><p>{f[1]}</p></details>)}</div></section>
<section className="contact" id="contact"><div><p className="eyebrow">07 / PRIVATE INQUIRY</p><h2>Every legacy begins<br/>with a conversation.</h2><p>Tell us only what feels comfortable. We will respond personally to arrange a private discovery call.</p><address><a href="mailto:hello@greenroadfilms.com">hello@greenroadfilms.com</a><a href="tel:+14155550186">+1 415 555 0186</a><span>San Francisco Bay Area, California</span></address></div>{sent?<div className="sent"><h3>Thank you.</h3><p>Connect this form to the client’s email or CRM before launch.</p><button onClick={()=>setSent(false)}>Send another inquiry</button></div>:<form onSubmit={submit}><label>Name<input required/></label><label>Email<input type="email" required/></label><label>Phone<input/></label><label>Story<select defaultValue=""><option value="" disabled>Select one</option>{stories.map(s=><option key={s[0]}>{s[0]}</option>)}</select></label><label className="wide">What would you like to preserve?<textarea rows={5} required/></label><button>Begin the conversation ↗</button></form>}</section>
<footer><div className="logo"><b>GREEN ROAD</b><small>FAMILY LEGACY FILMS</small></div><p>Your story, carried forward.</p><div><span>San Francisco · Northern California</span><span>© 2026 Green Road Films, LLC</span><span>Demo photography / Pexels</span></div></footer></main>}
